services:
  fluentd:
    container_name: fluentd
    image: psyoblade/data-engineer-fluentd:2.2
    depends_on: 
      - namenode
      - datanode
    user: root
    tty: true
    volumes:
      - ./fluentd/fluent.conf:/etc/fluentd/fluent.conf
    ports:
      - 9880:9880
    networks:
      - default
    entrypoint: [ "fluentd" ]

  namenode:
    container_name: namenode
    image: bde2020/hadoop-namenode:1.1.0-hadoop2.8-java8
    volumes:
      - namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop/hadoop.env
    ports:
      - 50070:50070

  datanode:
    container_name: datanode
    image: bde2020/hadoop-datanode:1.1.0-hadoop2.8-java8
    depends_on: 
      - namenode
    volumes:
      - datanode:/hadoop/dfs/data
    env_file:
      - ./hadoop/hadoop.env
    ports:
      - 50075:50075

volumes:
  namenode:
  datanode:

networks:
  default:
    name: day2_ex9_network
