services:
  fluentd:
    container_name: fluentd
    image: psyoblade/data-engineer-fluentd:2.2
    user: root
    tty: true
    ports:
      - 9881:9880
    volumes:
      - ./fluent.conf:/etc/fluentd/fluent.conf
      - ./send_http.sh:/home/root/send_http.sh
    working_dir: /home/root

networks:
  default:
    name: day2_quiz1_network
