services:
  fluentd:
    container_name: fluentd
    image: psyoblade/data-engineer-fluentd:2.2
    user: root
    tty: true
    volumes:
      - ./fluent.conf:/etc/fluentd/fluent.conf
      - ./target:/fluentd/target
    working_dir: /home/root

networks:
  default:
    name: day2_quiz2_network
